In [20]:
## chainer使用時に必要となるオブジェクトのimport(毎回定義)
import chainer
from chainer import cuda, Function, gradient_check,\
    Variable, optimizers, serializers, utils
from chainer import Link, Chain, ChainList
import chainer.functions as F
import chainer.link as L
import numpy as np

In [21]:
## chainerの変数=NNグラフのノードはVariableクラスで生成
## Variableの引数にはnumpyの配列を入力
## 変数タイプはfloat32, またはint32
x1 = Variable(np.array([1], dtype=np.float32))
x2 = Variable(np.array([2], dtype=np.float32))
x3 = Variable(np.array([3], dtype=np.float32))

In [29]:
## x1はサイズ1で値が1の配列
np.size(x1)

1

In [30]:
x1.data

array([ 1.], dtype=float32)

In [31]:
## 変数型を変更してVariableに登録する
x1 = Variable(np.array([1]).astype(np.float32))

In [32]:
## Variableで演算するとVariableになる
z = (x1 - 2 * x2 - 1)**2 + (x2 * x3 - 1)**2 + 1
z.data # (1-2*2-1)**2+(2*3-1)**2+1=42

array([ 42.], dtype=float32)

In [33]:
## zの微分値を計算する
z.backward()

In [34]:
## x1,x2,x3に関する偏微分値を出力
x1.grad, x2.grad, x3.grad

(array([-8.], dtype=float32),
 array([ 46.], dtype=float32),
 array([ 20.], dtype=float32))