In [1]:
import numpy as np
from chainer import cuda, Function, gradient_check,\
    Variable, optimizers, serializers, utils
from chainer import Link, Chain, ChainList
import chainer.functions as F
import chainer.links as L

In [2]:
## functionモジュールで提供される関数例：sin(x)
## Variableを変数とする
x = Variable(np.array([-1], dtype=np.float32))
F.sin(x).data

array([-0.84147096], dtype=float32)

In [3]:
## functionモジュールで提供される関数例：sigmoid(x)
F.sigmoid(x).data

array([ 0.2689414], dtype=float32)

In [4]:
## 微分値が求められていることを確認する
x = Variable(np.array([-0.5], dtype=np.float32))
z = F.cos(x)
z.backward()
x.grad

array([ 0.47942555], dtype=float32)

In [5]:
# cos(x=-0.5)の微分値は-sin(x=-0.5)
((-1)*F.sin(x)).data

array([ 0.47942555], dtype=float32)

In [9]:
## 変数が多次元で微分値を求める場合、全要素1で初期化しておく
x = Variable(np.array([-1,0,1], dtype=np.float32))
z = F.sin(x)
z.grad = np.ones(3, dtype=np.float32) #全要素1
z.backward()
x.grad

array([ 0.54030228,  1.        ,  0.54030228], dtype=float32)

In [10]:
## ネットワーク(Link)の生成
## 3次元入力→4次元出力への変換
h = L.Linear(3,4)
## ネットワークの重みWは最初は乱数
h.W.data

array([[-0.28921488, -0.27544841, -0.11872956],
       [ 0.12522155, -1.47503114, -0.15101415],
       [-0.84136558, -0.50418878, -0.77031749],
       [-0.60373098,  0.5018304 , -0.31641877]], dtype=float32)

In [11]:
## バイアスには0が入っている
h.b.data

array([ 0.,  0.,  0.,  0.], dtype=float32)

In [12]:
## ネットワークの入力データはバッチで与える
## 入力が3次元なので3個データの組み合わせがN個分
x = Variable(np.array(range(6)).astype(np.float32).reshape(2,3))
x.data

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.]], dtype=float32)

In [14]:
## 3次元のデータ2組を入力として与える
y = h(x)
y.data

array([[-0.51290751, -1.77705944, -2.04482365, -0.13100713],
       [-2.56308603, -6.27953053, -8.39243889, -1.38596523]], dtype=float32)

In [ ]:
## 行列の演算でテスト
w = h.W.data
x0 = x.data
x0.dot(w.T) + h.b.data